# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: pengj 

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "Peng Talk"

description: 
author:
  name: Peng
  email: peng.jiang@live.com
  github: pengj
  linkedin: pengj1
  bio: A Geeky adventures
  email_md5: ce01b522dfb3e646a1326c20dafc2229

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
